// <auto-generated />
using CliientApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CliientApp.Migrations
{
    [DbContext(typeof(ChatRoomDbContext))]
    [Migration("20230406062108_editing")]
    partial class editing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CliientApp.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IPEndPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Clients", null, t =>
                        {
                            t.HasCheckConstraint("Login", "Login != ''");

                            t.HasCheckConstraint("Password", "Password != '' AND Password LIKE N'[^./%$#@,]%'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "User1",
                            Password = "1111"
                        },
                        new
                        {
                            Id = 2,
                            Login = "User2",
                            Password = "2222"
                        },
                        new
                        {
                            Id = 3,
                            Login = "User3",
                            Password = "3333"
                        },
                        new
                        {
                            Id = 4,
                            Login = "User4",
                            Password = "4444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
